version: '3.9'
services:
  my-cron-job:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-cron-job-container
    environment:
      - SOCKET_ON_THRESHOLD=98
      - SOCKET_OFF_THRESHOLD=100
      - HUE_BRIDGE_IP=${HUE_BRIDGE_IP}
      - HUE_BRIDGE_USERNAME=${HUE_BRIDGE_USERNAME}
      - HUE_BRIDGE_SOCKET_ID=${HUE_BRIDGE_SOCKET_ID}
      - BATTERY_PERCENTAGE_FILE=/battery_capacity
    volumes:
      - /sys/class/power_supply/BAT1/capacity:/battery_capacity:ro
    network_mode: host
    restart: always
